# Generated by Django 3.1.5 on 2022-05-29 22:36

import asteroid.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('item_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='WikiMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=asteroid.models.path_and_name)),
                ('mtags', models.CharField(max_length=512)),
                ('med_itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75)),
                ('item_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=128)),
                ('datos', models.TextField()),
                ('tbl_itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.item')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('con_itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.item')),
            ],
        ),
    ]
