# Generated by Django 3.1.5 on 2022-06-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0003_auto_20220619_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goles',
            name='og',
            field=models.BooleanField(default=False),
        ),
    ]
