# Generated by Django 3.1.5 on 2022-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0005_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='cfecha',
            field=models.DateField(default='2022-09-14'),
        ),
    ]
