# Generated by Django 3.1.5 on 2023-01-16 14:03

import asteroid.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0006_coleccion_cfecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTableMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=asteroid.models.path_and_name)),
                ('mtags', models.CharField(max_length=512)),
                ('itm_tbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.itemtable')),
            ],
        ),
    ]
