# Generated by Django 4.0.6 on 2023-04-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0010_baseballgame_fase_baseballgame_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='season',
            field=models.IntegerField(default=0),
        ),
    ]
