# Generated by Django 4.2.2 on 2023-07-08 21:57

import asteroid.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0014_grupo_persona_relgrupopersona_personamedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to=asteroid.models.path_and_name)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.notes')),
            ],
        ),
    ]
