# Generated by Django 4.2.2 on 2023-08-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0015_notemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelItemPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=256)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.item')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
            ],
        ),
    ]
