# Generated by Django 4.0.6 on 2023-09-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0019_contrato_number_contrato_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_fecha', models.DateField()),
                ('progreso', models.IntegerField()),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.consumo')),
            ],
        ),
    ]
