# Generated by Django 4.0.6 on 2023-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0020_consumohist'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumohist',
            name='anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumohist',
            name='nowcon',
            field=models.IntegerField(default=0),
        ),
    ]
