# Generated by Django 4.2.2 on 2023-11-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0022_remove_baseballgame_local_remove_baseballgame_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(default='no-asignado', max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='desc',
            field=models.TextField(default='TBD'),
        ),
        migrations.CreateModel(
            name='PartidoFutbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visit', models.IntegerField(default=0)),
                ('terminado', models.IntegerField(default=0)),
                ('liga', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_t', to='asteroid.grupo')),
                ('equipo_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_v', to='asteroid.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('adicional', models.IntegerField()),
                ('penal', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.grupo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.partidofutbol')),
            ],
        ),
        migrations.CreateModel(
            name='attFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=255)),
                ('valor', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
            ],
        ),
        migrations.CreateModel(
            name='attEntero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
            ],
        ),
        migrations.CreateModel(
            name='attDecimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
            ],
        ),
        migrations.CreateModel(
            name='attCadena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=255)),
                ('valor', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
            ],
        ),
    ]
