# Generated by Django 4.2.2 on 2023-11-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0023_grupo_tipo_alter_grupo_desc_partidofutbol_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDT', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.persona')),
            ],
        ),
    ]
