# Generated by Django 4.2.2 on 2023-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0025_contrato_equipo_jugador_liga_partido_penales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidocomment',
            name='minuto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partidocomment',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
