# Generated by Django 4.2.2 on 2024-01-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0026_partidocomment_minuto_partidocomment_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('bio', models.TextField()),
                ('tabla', models.TextField(default='blank')),
                ('fechaM', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.item')),
            ],
        ),
    ]
