# Generated by Django 4.2.2 on 2024-01-13 19:48

import asteroid.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0027_wikichild'),
    ]

    operations = [
        migrations.CreateModel(
            name='WCMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=asteroid.models.path_and_name)),
                ('wikichild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroid.wikichild')),
            ],
        ),
    ]
