# Generated by Django 4.2.2 on 2024-03-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0028_wcmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlbTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('nomina', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mlbGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('local_runs', models.IntegerField()),
                ('visit_runa', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='asteroid.mlbteam')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_team', to='asteroid.mlbteam')),
            ],
        ),
    ]
