from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('plantilla/', views.plantilla, name='plantilla'),
	path('', views.homepage, name='homepage'),
	path('archive/<p>', views.archive, name='archive'),
	path('c/<cat>/<p>', views.category, name='category'),
	path('q/<cat>/<p>', views.catqueue, name='catqueue'),
	path('search/', views.search, name='search'),
	path('additem', views.additem, name='additem'),
	path('item/<iid>', views.item, name='item'),
	path('edititem/<iid>', views.edititem, name='edititem'),
	path('startitem/<iid>', views.startitem, name='startitem'),
	path('tableitem/<iid>', views.tableitem, name='tableitem'),
	path('addmedia/<iid>', views.addMedia, name='addMedia'),
	path('finance/', views.finance, name='finance'),
	path('financemob/', views.finance2, name='finance2'),
	path('savetrx/', views.saveTrx, name='savetrx'),
	path('savepmt/', views.savePmt, name='savepmt'),
	path('addcoleccion/', views.addColeccion, name='addcoleccion'),
	path('coleccion/<id>', views.coleccion, name='coleccion'),
	path('cocovers/<id>/<s>', views.cocovers, name='cocovers'),
	path('additmcol/<it>/<co>', views.additmcol, name='additmcol'),
	path('addmatch/<lid>/', views.addPartido, name='addmatch'),
	path('viewmatches/<sta>/', views.viewMatches, name='viewmatches'),
	path('viewmatch/<pid>/', views.viewMatch, name='viewmatch'),
	path('closematch/<pid>/', views.closeMatch, name='closematch'),
	path('viewliga/<sta>/<lig>', views.viewLiga, name='viewliga'),
	path('addcontract/<pid>', views.addContract, name='addcontract'),
	path('regpenround/<pid>', views.regPenRound, name='regpenround'),
	path('autor/<au>', views.autor, name='autor'),
	path('view-month/<y>/<m>', views.viewmonth, name='viewmonth'),
	path('quemar/<itm>', views.quemar, name='quemar'),
	path('team/<t>', views.sccteam, name='sccteam'),
	path('addsecleg/', views.addsecleg, name='addsecleg'),
	path('addjournalentry/', views.addJournalEntry, name='addJournalEntry'),
	path('edit-itt/<tid>', views.editTable, name='edit-itt'),
	path('year-hist/<y>/<c>', views.yearHist, name='yearHist'),
	path('add-ittmedia/', views.addIttMedia, name='addIttMedia'),
	path('add-ittmedia/', views.addIttMedia, name='addIttMedia'),
	path('jugadores/', views.jugadores, name='jugadores'),
	path('jugador/<jid>', views.jugador, name='jugador'),
	path('addpartidocomm/',views.addpartidocomm,name="addpartidocomm"),
	path('publish/<col_id>', views.forKindle, name='kindlePublish'),
	path('addmlbteam/', views.addBaseballTeam, name='addBbTeam'),
	path('addmlbgame/', views.addBaseballGame, name='addBbGame'),
	path('mlbgames/', views.mlbGames, name='mlbGames'),
	path('mlbgame/<id>', views.mlbGame, name='mlbGame'),
	path('atbat/<gameid>', views.atbat, name='mlbAtBat'),
	path('pitch/<gameid>', views.pitching, name='mlbPitch'),
	path('viewtag/<t>', views.viewtag, name='itag'),
	path('viewseason/<season>', views.viewBaseballSeason, name='bbseason'),
	path('addplayerv2/', views.addPlayerv2, name='addplayerv2'),
	path('add-notes/<item_id>', views.addNotes, name='addnotes'),
	path('edit-notes/<note_id>', views.editNotes, name='editnotes'),
	path('addbudget/',views.addBudgetReg,name='addBudget'),
    path('mlbPendingGames/', views.mlbPendingGames, name='mlbPendingGames'),
    path('updateBaseballGame/', views.updateBaseballGame, name='updateBaseballGame'),

    path('diradb/', views.plantilla2, name='plantilla2'),
	path('add-persona/', views.addPersona, name='add-persona'),
	path('view-ppl/<t>/<p>', views.viewPersonas, name='view-ppl'),
	path('view-persona/<p>', views.viewPersona, name='view-persona'),
	path('edit-persona/<p>', views.editPersona, name='edit-persona'),
	path('add-media-persona/', views.addPersonaMedia, name='add-media-persona'),
	path('view-pg/<p>/<n>', views.viewPersonaGallery, name='view-pg'),
	path('view-g/<g>/<p>', views.viewGrupo, name='view-g'),
	path('viewr/', views.viewr, name='viewr'),
	path('relacionarPG/<p>/<g>',views.relacionarPG,name='relacionarPG'),
	path('movie-import/<movie_id>/',views.moviedbImport,name='moviedbImport'),
	path('togetmovie/',views.togetmovie,name='togetmovie'),
	path('startNC/',views.startNoteConsumo,name='startNoteConsumo'),
	path('finishNC/',views.finishNoteConsumo,name='finishNoteConsumo'),
	path('add-soccer-team/',views.addSoccerTeam,name='addSoccerTeam'),
	path('add-item-credits/',views.addItemCredits,name='addItemCredits'),
]