# Generated by Django 4.0.6 on 2023-04-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0009_baseballcontract_baseballgame_baseballplayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballgame',
            name='fase',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='stadium',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
