# Generated by Django 3.1.5 on 2022-06-29 14:27

from django.db import migrations, models
import django.db.models.deletion
import garden.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=garden.models.media_path)),
                ('ptags', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('petal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.petal')),
            ],
        ),
    ]
